[project]
name = "simple_crud_app"
version = "0.1.0"
description = "This is a simple StarSpring CRUD web application to demonstrate how the internals works."
requires-python = ">=3.14"
dependencies = [
    "starspring>=0.1.2",
]
